Multi period investment
oemof/oemof-tabular pull request #108
Opened 2023-07-04 14:05 UTC by nailend

- Added additional lifetime parameter to certain facades
- Added constraint test for multi-period approach
- Added LP files

2023-07-05 06:23 UTC, henhuy commented
As I remember there was an `age` parameter in MP-feature - shouldn't facades provide it too?

2023-07-05 06:45 UTC, nailend commented
> As I remember there was an `age` parameter in MP-feature - shouldn't facades provide it too?

You are right. Sorry, I only fixed what was necessary to make it run. Will rework it.

2023-07-18 09:43 UTC, henhuy requested changes
I encountered an error when lifetime is set but age is set to default "None" - age default should be set to zero - will add a failing test.

2023-07-18 13:30 UTC, nailend commented on src/oemof/tabular/facades/volatile.py
> +    age: int = None
Thanks for checking this!

2023-07-18 13:30 UTC, merged