Periodic value deserialization
oemof/oemof-tabular pull request #124
Opened 2023-08-24 12:42 UTC by nailend

close #115

2023-10-04 20:00 UTC, nailend commented
Change in [oemof.solph issue 983](https://github.com/oemof/oemof-solph/issues/983) might have an effect on this

2023-10-06 10:13 UTC, henhuy requested changes
Minor change requested. Otherwise this looks good to me.

2023-10-06 10:13 UTC, henhuy commented on src/oemof/tabular/datapackage/reading.py
> +        if len(values) == len(periods_index):
would check for inequality and remove pass statement

2023-10-06 10:13 UTC, henhuy commented on src/oemof/tabular/datapackage/reading.py
> +                                warnings.warn(msg, UserWarning)
The message does not belong here, as paramter has not been converted.
Instead, I would replace whole part with simple `continue` as value does not has to be adapted...

2023-10-11 10:56 UTC, nailend commented
@henhuy not sure what's happening here and why the tests fail. Locally, there is no error ... Could you please check locally as well?

2023-10-12 10:43 UTC, henhuy commented
I could reproduce error with latest python version 3.9.18 - in 3.9.16 error did not occur.
Could not figure out what has been changed in between those versions, though.
Error comes up, as `Flow` component "has" an attribute `_in_edges`, but for some reasons the attribute cannot be accessed and therefor throws an error:
https://github.com/oemof/oemof-solph/blob/f02297ea7db0134bfff12c3ff6c7c909ca4405ed/src/oemof/solph/processing.py#L515-L532
Fix could be to reverse checking:
```
attrs = [
    i
    for i in dir(com)
    if not (i.startswith(exclusions) or callable(getattr(com, i)))
]
```
We could implement this fix in `oemof.solph` - but first we would have to add a failing test to show and explain what's happening.

2023-10-12 15:36 UTC, nailend commented
Strange... python version 3.9.18 is from August'23 and was also already used in this [CI run](https://github.com/oemof/oemof-tabular/actions/runs/6422187115/job/17438171580) which wasn't failing.

2023-10-12 16:28 UTC, nailend commented
I found it. Its caused by changes in  `oemof.network` apparently version `0.5.0a1` was still working

2023-10-12 16:51 UTC, p-snft commented
Unfortunately, network has some untested and undocumented parts. I did a release that did not really change anything to the "official" API.

I already reversed the check that @henhuy mentioned in a branch of solph. I will rush the PT and make a release.

2023-10-12 18:20 UTC, p-snft commented
There now is [oemof.solph 0.5.2.dev0](https://pypi.org/project/oemof.solph/0.5.2.dev0/) that should fix the issue.

2023-10-16 15:03 UTC, merged